/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as OwnerRepoPullsRouteImport } from './routes/$owner/$repo/pulls'
import { Route as OwnerRepoIssuesRouteImport } from './routes/$owner/$repo/issues'
import { Route as OwnerRepoPullNumberRouteImport } from './routes/$owner/$repo/pull/$number'
import { Route as OwnerRepoIssueNumberRouteImport } from './routes/$owner/$repo/issue/$number'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRepoPullsRoute = OwnerRepoPullsRouteImport.update({
  id: '/$owner/$repo/pulls',
  path: '/$owner/$repo/pulls',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRepoIssuesRoute = OwnerRepoIssuesRouteImport.update({
  id: '/$owner/$repo/issues',
  path: '/$owner/$repo/issues',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRepoPullNumberRoute = OwnerRepoPullNumberRouteImport.update({
  id: '/$owner/$repo/pull/$number',
  path: '/$owner/$repo/pull/$number',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRepoIssueNumberRoute = OwnerRepoIssueNumberRouteImport.update({
  id: '/$owner/$repo/issue/$number',
  path: '/$owner/$repo/issue/$number',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/$owner/$repo/issues': typeof OwnerRepoIssuesRoute
  '/$owner/$repo/pulls': typeof OwnerRepoPullsRoute
  '/$owner/$repo/issue/$number': typeof OwnerRepoIssueNumberRoute
  '/$owner/$repo/pull/$number': typeof OwnerRepoPullNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/$owner/$repo/issues': typeof OwnerRepoIssuesRoute
  '/$owner/$repo/pulls': typeof OwnerRepoPullsRoute
  '/$owner/$repo/issue/$number': typeof OwnerRepoIssueNumberRoute
  '/$owner/$repo/pull/$number': typeof OwnerRepoPullNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/$owner/$repo/issues': typeof OwnerRepoIssuesRoute
  '/$owner/$repo/pulls': typeof OwnerRepoPullsRoute
  '/$owner/$repo/issue/$number': typeof OwnerRepoIssueNumberRoute
  '/$owner/$repo/pull/$number': typeof OwnerRepoPullNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo/tanstack-query'
    | '/$owner/$repo/issues'
    | '/$owner/$repo/pulls'
    | '/$owner/$repo/issue/$number'
    | '/$owner/$repo/pull/$number'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo/tanstack-query'
    | '/$owner/$repo/issues'
    | '/$owner/$repo/pulls'
    | '/$owner/$repo/issue/$number'
    | '/$owner/$repo/pull/$number'
  id:
    | '__root__'
    | '/'
    | '/demo/tanstack-query'
    | '/$owner/$repo/issues'
    | '/$owner/$repo/pulls'
    | '/$owner/$repo/issue/$number'
    | '/$owner/$repo/pull/$number'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  OwnerRepoIssuesRoute: typeof OwnerRepoIssuesRoute
  OwnerRepoPullsRoute: typeof OwnerRepoPullsRoute
  OwnerRepoIssueNumberRoute: typeof OwnerRepoIssueNumberRoute
  OwnerRepoPullNumberRoute: typeof OwnerRepoPullNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$repo/pulls': {
      id: '/$owner/$repo/pulls'
      path: '/$owner/$repo/pulls'
      fullPath: '/$owner/$repo/pulls'
      preLoaderRoute: typeof OwnerRepoPullsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$repo/issues': {
      id: '/$owner/$repo/issues'
      path: '/$owner/$repo/issues'
      fullPath: '/$owner/$repo/issues'
      preLoaderRoute: typeof OwnerRepoIssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$repo/pull/$number': {
      id: '/$owner/$repo/pull/$number'
      path: '/$owner/$repo/pull/$number'
      fullPath: '/$owner/$repo/pull/$number'
      preLoaderRoute: typeof OwnerRepoPullNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$repo/issue/$number': {
      id: '/$owner/$repo/issue/$number'
      path: '/$owner/$repo/issue/$number'
      fullPath: '/$owner/$repo/issue/$number'
      preLoaderRoute: typeof OwnerRepoIssueNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  OwnerRepoIssuesRoute: OwnerRepoIssuesRoute,
  OwnerRepoPullsRoute: OwnerRepoPullsRoute,
  OwnerRepoIssueNumberRoute: OwnerRepoIssueNumberRoute,
  OwnerRepoPullNumberRoute: OwnerRepoPullNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
